-- MySQL Script generated by MySQL Workbench
-- Thu Mar 15 11:23:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbSistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbSistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbSistema` DEFAULT CHARACTER SET utf8 ;
USE `dbSistema` ;

-- -----------------------------------------------------
-- Table `dbSistema`.`Distribuidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSistema`.`Distribuidor` (
  `idDistribuidor` INT NOT NULL,
  `nombreDistribuidor` VARCHAR(45) NOT NULL,
  `nitDistribuidor` VARCHAR(45) NOT NULL,
  `direccionDistribuidor` VARCHAR(200) NOT NULL,
  `telefonoDistribuidor` INT NOT NULL,
  `telEmeregenciaDistribuidor` INT NOT NULL,
  `emailDistribuidor` VARCHAR(45) NOT NULL,
  `comentariosDistribuidor` VARCHAR(200) NULL,
  PRIMARY KEY (`idDistribuidor`),
  UNIQUE INDEX `nombreDistribuidor_UNIQUE` (`nombreDistribuidor` ASC),
  UNIQUE INDEX `nitDistribuidor_UNIQUE` (`nitDistribuidor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSistema`.`SucursalProveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSistema`.`SucursalProveedor` (
  `idSucursalProveedor` INT NOT NULL AUTO_INCREMENT,
  `paisProveedor` VARCHAR(45) NOT NULL,
  `departamentoProveedor` VARCHAR(45) NOT NULL,
  `direccionProveedor` VARCHAR(100) NOT NULL,
  `telefonoProveedor` VARCHAR(45) NOT NULL,
  `nombreContactoProveedor` VARCHAR(45) NOT NULL,
  `comentariosProveedor` VARCHAR(200) NULL,
  `codigoPostalProveedor` VARCHAR(45) NOT NULL,
  `emailProveedor` VARCHAR(45) NOT NULL,
  `nitSucursalProveedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSucursalProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSistema`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSistema`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `nombreProveedor` VARCHAR(45) NOT NULL,
  `direccionProveedor` VARCHAR(45) NOT NULL,
  `nitProveedor` VARCHAR(45) NOT NULL,
  `telProveedor` INT NOT NULL,
  `webProveedor` VARCHAR(45) NULL,
  `idSucursal` INT NOT NULL,
  PRIMARY KEY (`idProveedor`),
  UNIQUE INDEX `nombreProveedor_UNIQUE` (`nombreProveedor` ASC),
  UNIQUE INDEX `nitProveedor_UNIQUE` (`nitProveedor` ASC),
  INDEX `FK_proveedor_sucursalProveedor_idx` (`idSucursal` ASC),
  CONSTRAINT `FK_proveedor_sucursalProveedor`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `dbSistema`.`SucursalProveedor` (`idSucursalProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSistema`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSistema`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `precioProducto` VARCHAR(45) NOT NULL,
  `stockProducto` VARCHAR(45) NOT NULL,
  `IDProveedor` INT NOT NULL,
  `IDDistribuidor` INT NOT NULL,
  `estadoProducto` VARCHAR(45) NULL,
  PRIMARY KEY (`idProducto`),
  UNIQUE INDEX `nombreProducto_UNIQUE` (`nombreProducto` ASC),
  INDEX `FK_producto_distribuidor_idx` (`IDDistribuidor` ASC),
  INDEX `FK_producto_proveedor_idx` (`IDProveedor` ASC),
  CONSTRAINT `FK_producto_distribuidor`
    FOREIGN KEY (`IDDistribuidor`)
    REFERENCES `dbSistema`.`Distribuidor` (`idDistribuidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_producto_proveedor`
    FOREIGN KEY (`IDProveedor`)
    REFERENCES `dbSistema`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
